//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WishlistApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Picture
    {
        public Picture()
        {
            this.ProfilePictures = new HashSet<ProfilePicture>();
        }
    
        public int PictureId { get; set; }
        public int UserId { get; set; }
        public byte[] Thumbnail128 { get; set; }
        public byte[] Content { get; set; }
        public System.DateTime TimeUtc { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual ICollection<ProfilePicture> ProfilePictures { get; set; }
    }
}
